version: '3.8'
services:
  api:
    container_name: rest-api-ya-school22
    build: ./
    ports:
      - "80:80"
    depends_on:
      - files_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://files_db:5432/rest_api_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  files_db:
    container_name: rest-api-postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    restart: always